zero_c: zero_value_test.c
	clang $< -o $@ 

run_zero_c: zero_c  
	./$<

zero_cpp: zero_value_test.cpp
	clang++ $< -o $@

run_zero_cpp: zero_cpp 
	./$<

inverse_sqrt: inverse_sqrt.c
	clang $< -o $@
	./$@





