@startuml
'https://plantuml.com/sequence-diagram

autonumber

User -----> TicketSystem: searchTrain(trainID)
TicketSystem -----> TrainDatabase: getTrainDetails(trainID)
TrainDatabase -----> TicketSystem: return trainDetails
TicketSystem -----> User: displayTrainDetails(trainDetails)

User -----> TicketSystem: purchaseTicket(trainID, userID)
TicketSystem -----> UserDatabase: getUserDetails(userID)
UserDatabase -----> TicketSystem: return userDetails
TicketSystem -----> PaymentSystem: processPayment(userDetails, trainDetails)
PaymentSystem -----> TicketSystem: return paymentConfirmation
TicketSystem -----> User: displayConfirmation(paymentConfirmation)

@enduml